# Generated by Django 4.1.13 on 2024-08-07 20:21

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('author', models.TextField(max_length=200)),
                ('isbn', models.CharField(max_length=100, unique=True)),
                ('published_date', models.PositiveBigIntegerField()),
                ('genre', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('copies_available', models.PositiveIntegerField()),
                ('total_copies', models.PositiveIntegerField()),
                ('publisher', models.TextField(null=True)),
                ('language', models.TextField(max_length=30)),
                ('keywords', djongo.models.fields.JSONField(default=list)),
                ('shelf_location', models.CharField(max_length=250)),
                ('added_date', models.PositiveBigIntegerField()),
                ('last_updated_date', models.PositiveBigIntegerField(null=True)),
                ('status', models.CharField(choices=[('0', 'Inactive'), ('1', 'Active')], default='1', max_length=1)),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
